# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches:
      - main  # 또는 배포하고 싶은 브랜치

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:${{ secrets.DOCKER_TAG || 'latest' }} .

      - name: Save Docker image to tarball
        run: |
          docker save ${{ secrets.DOCKER_IMAGE_NAME }}:${{ secrets.DOCKER_TAG || 'latest' }} -o ${{secrets.DOCKER_IMAGE_NAME}}_image.tar
          chmod 644 ${{secrets.DOCKER_IMAGE_NAME}}_image.tar

      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./${{secrets.DOCKER_IMAGE_NAME}}_image.tar"
          target: "~/app"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/app
            docker load -i ${{secrets.DOCKER_IMAGE_NAME}}_image.tar
            docker stop app-container || true
            docker rm app-container || true
            docker run -d --name app-container -p 80:80 ${{ secrets.DOCKER_IMAGE_NAME }}:${{ secrets.DOCKER_TAG || 'latest' }}
