name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ secrets.DOCKER_TAG || 'latest' }}
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > ${{ secrets.DOCKER_IMAGE_NAME }}.env

      - name: Copy .env to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./${{ secrets.DOCKER_IMAGE_NAME }}.env"
          target: "~/app"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ secrets.DOCKER_TAG || 'latest' }}
            cd ~/app
            docker stop backend-app-container || true
            docker rm backend-app-container || true
            docker pull $IMAGE
            docker run --env-file ${{ secrets.DOCKER_IMAGE_NAME }}.env -d --restart always --name backend-app-container -p 8000:8000 $IMAGE
