name: Deploy to Dev

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo '${{ secrets.ENV_FILE }}' > .env

      - name: Docker Compose Up (local build)
        run: docker compose --env-file .env up -d

      - name: Remove .env file
        run: rm .env

      - name: Clean up unused images (optional)
        run: docker image prune -af
