name: Deploy to Dev

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout code (if needed)
        uses: actions/checkout@v4

      - name: Prepare temporary Docker config (to avoid macOS Keychain)
        run: |
          mkdir -p /tmp/docker-config
          echo '{}' > /tmp/docker-config/config.json

      - name: Docker Login (No Keychain)
        run: |
          echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker --config /tmp/docker-config login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create .env file from Secret
        run: |
          echo '${{ secrets.ENV_FILE }}' > .env

      - name: Deploy with Docker Compose
        env:
          DOCKER_CONFIG: /tmp/docker-config
        run: |
          COMPOSE_FILE_PATH="./docker-compose.yaml"
          ENV_FILE_PATH="./.env"
          APP_SERVICE_NAME="backend-app-container"

          docker compose -f $COMPOSE_FILE_PATH --env-file $ENV_FILE_PATH pull $APP_SERVICE_NAME
          docker compose -f $COMPOSE_FILE_PATH --env-file $ENV_FILE_PATH up -d --no-deps $APP_SERVICE_NAME

      - name: Remove .env file
        run: rm .env

      - name: Clean up unused docker images (Optional)
        run: docker image prune -af
